### ISSUE TITLE
unable to bind shortcuts

### ISSUE THREAD

**Issue by storrgie** [flathub/info.mumble.Mumble#12]
I'm unable to assign shortcuts, so I can't use push-to-talk

**Comment by TingPing** [comment]
Any info about the system like do you happen to use Wayland?

**Comment by storrgie** [comment]
Yes, apologies, I'm on Fedora 32 Silverblue which is using wayland.

**Comment by TingPing** [comment]
Well then its not expected to work. There is no method to capture global keypresses on Wayland currently.

**Comment by JBBgameich** [comment]
Since this is currently not fixable in this repository, I'm going to close the issue. In case there are any issues that can be fixed in this repository, please comment and reopen the issue.
