### ISSUE TITLE
Mumble 1.4.230 is missing PipeWire as audio subsystem

### ISSUE THREAD

**Issue by Gert-dev** [flathub/info.mumble.Mumble#19]
## Problem

[The release notes for 1.4.230](https://www.mumble.info/blog/mumble-1.4.230/) mention that it has PipeWire support on the following line:

> Added: Native support for PipeWire (#4970)

In the past, I've taken this for a test drive using `mumble-git` from the AUR on Arch Linux, and it worked well, but, now that the stable version is released, it seems to be missing as option from the Flatpak version.

## Steps To Reproduce

1. Open the settings window.
2. Go to Audio Input settings.
3. Click open the audio subsystem dropdown; ALSA, JACK and PulseAudio are listed, but not PipeWire.

## Expected Result / Possible Solutions

PipeWire is listed as an available option.

## Additional Info

This could well be an upstream issue with Mumble itself, as it dynamically detects which subsystems are available; for example, if you take away the PulseAudio Flatpak permission, it won't show PulseAudio, as expected. It could also be tha PipeWire requires an additional Flatpak permission. If it's an upstream issue, I'll be happy to report it there.

I'd compare it with the stable Mumble from the Arch Linux repos, but 1.4.230 is not packaged yet officially. I can test it against the native version as soon as it's available in case it helps.

* Version: 1.4.230
* Operating System / Distribution: Arch Linux x86-64
* Desktop Environment: GNOME 41.3
* Kernel Version: 5.16.0

Thanks for maintaining this!

**Comment by JBBgameich** [comment]
My flatpak version doesn't have a permission for pipewire, but it's possible that it's just too old. I'm already using Pipewire too though, but through pipewire-pulse, and that works.

If you know the name of the permission (and it doesn't break older flatpak versions), I can add it of course.

**Comment by Gert-dev** [comment]
Indeed, I also use PipeWire to emulate PulseAudio and it works fine using the PulseAudio subsystem. Mumble 1.4.230 should now also support using PipeWire directly, though, which may result in lower CPU usage. 

I've been looking around a bit, and I don't know enough about flatpaks, but does Flathub automatically build applications from source based on the configuration provided here? If so, it might be necessary to ensure PipeWire is available in the build environment, since I think Mumble checks if PipeWire is available as build time dependency ([the AUR package also added it](https://aur.archlinux.org/cgit/aur.git/commit/?h=mumble-git&id=1597ec6b10e7882343eb8505d9f485776f764e26)).

I've been staring at [how the Flatpak-ed PulseEffects does it](https://github.com/flathub/com.github.wwmm.easyeffects/blob/master/com.github.wwmm.easyeffects.yml#L215), and it looks like it directly includes PipeWire, but it may be a different case altogether. Another thing they do is [add `--filesystem=xdg-run/pipewire-0:ro`](https://github.com/flathub/com.github.wwmm.easyeffects/blob/master/com.github.wwmm.easyeffects.yml#L13) (I can confirm that this isn't sufficient, though).

It could well be that the Flatpak permissions are not at fault, but that Mumble is looking for the libraries in the wrong places or doing an incorrect check to see if it is supported, though.

**Comment by JBBgameich** [comment]
> I've been looking around a bit, and I don't know enough about flatpaks, but does Flathub automatically build applications from source based on the configuration provided here?

Yes, the application is built from source in an Sdk that is the same for all apps, freedesktop-sdk. I'm pretty sure that already includes PipeWire, that's why JACK support successfully uses it.

Maybe the PipeWire we have in the flatpak is too old though.

**Comment by Gert-dev** [comment]
Good to know. I did some digging [around the subsystem source](https://github.com/mumble-voip/mumble/blob/5598fe82c7369c816ddac3cf51e1c5332351f71a/src/mumble/PipeWire.cpp), but can't immediately seem to find anything that does an "is supported" check here.

The original PR (https://github.com/mumble-voip/mumble/pull/4970) mentions it was tested with PipeWire 0.3.26; I don't know which version is part of the Flatpak. In any case, [the build seems to enable PipeWire by default if the libraries exist](https://github.com/mumble-voip/mumble/blob/master/src/mumble/CMakeLists.txt#L53).

Mumble prints some info pertaining to PulseAudio and JACK on startup, including `JACK 3.0.0.0 (using PipeWire 0.3.35) from libjack.so.0`, but no messages regarding the PipeWire subsystem itself.

**Comment by davidebeatrici** [comment]
0.3

**Comment by Gert-dev** [comment]
> I'd compare it with the stable Mumble from the Arch Linux repos, but 1.4.230 is not packaged yet officially. I can test it against the native version as soon as it's available in case it helps.

I tested Mumble 1.4.230 from the official Arch repositories today, now that it's packaged, and PipeWire is indeed exposed as subsystem for input and output.

I'm not familiar enough with Flatpak, but [some digging](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/master/elements/components/pipewire-base.bst#L113) implies that the latest runtime is on PipeWire >= 0.3.40 - though I'm not sure what version `org.kde.Platform` `5.15-21.08` is based on (I doubt it will have a much older version, though).

**Comment by JBBgameich** [comment]
5.15-21.08 is based on the freedesktop runtime 21.08

**Comment by Gert-dev** [comment]
I did some digging into the Mumble source code and the world of Flatpaks and I think this may be a Mumble issue. We already verified that PipeWire 3.35.0 is available in the runtime, and I verified that the PipeWire subsystem in Mumble tries to initialize in `PipeWireSystem::PipeWireSystem`, but it then proceeds to [scan for SO names](https://github.com/mumble-voip/mumble/blob/5598fe82c7369c816ddac3cf51e1c5332351f71a/src/mumble/PipeWire.cpp#L131), doesn't find any of those names, and then bails [a couple lines further](https://github.com/mumble-voip/mumble/blob/5598fe82c7369c816ddac3cf51e1c5332351f71a/src/mumble/PipeWire.cpp#L141).

@JBBgameich Before I report this upstream, do you have any idea how I can check what the proper SO names are inside the runtime? Since I now figured out how to build Mumble in a Flatpak myself, I can test changing the affected code until it works and then upstream a patch.

**Comment by JBBgameich** [comment]
Thanks for investigating! Did you already propose the fix upstream?

**Comment by Gert-dev** [comment]
[I did now!](https://github.com/mumble-voip/mumble/pull/5530).

**Comment by Gert-dev** [comment]
I also managed to fix the audio input and output not working :tada: , see also https://github.com/flathub/info.mumble.Mumble/pull/20.

**Comment by JBBgameich** [comment]
If the patch is relatively simple, I can just apply it on top of the stable release without pulling in the other chages. Thanks for fixing it upstream!

**Comment by Gert-dev** [comment]
I tested #21 and everything seems to work. I'll close this, thanks!
