### ISSUE TITLE
Please update to 1.3.0!

### ISSUE THREAD

**Issue by sofar** [flathub/info.mumble.Mumble#2]
Thanks!

**Comment by JBBgameich** [comment]
Done as https://github.com/flathub/info.mumble.Mumble/commit/2966fa61c5abaaec8f92c8642a718853734ee5d0, thanks to @corecontingency!

**Comment by sofar** [comment]
Neat-o. I threw it into `clearlinux` as well but it's great to have a flatpak around. The new version is great!
