### ISSUE TITLE
Latest version keeps saying there is a new version available when started

### ISSUE THREAD

**Issue by Pentaphon** [flathub/info.mumble.Mumble#22]
![Screenshot from 2022-01-28 03-20-28](https://user-images.githubusercontent.com/49374058/151538486-6dd073c0-fb40-4f07-9488-a71028881a2a.png)

**Comment by JBBgameich** [comment]
Can you try to submit this bug upstream? I don't think we are doing anything special here that would cause this.

**Comment by JBBgameich** [comment]
Maybe someone upstream forgot to update the version number in CMakeLists.txt after switching to the new versioning scheme

**Comment by maweil** [comment]
I can confirm this is not an issue with the official binaries (tested on Windows) for Mumble but only the flatpak release. 
It seems with commit https://github.com/mumble-voip/mumble/commit/8505df958fc16a6f3ad902d84aed415742c5bb20 there was a new config option `BUILD_NUMBER` added. This determines the last part of the version number. I'm currently preparing a PR to set it for the flatpak build as well.

**Comment by JBBgameich** [comment]
Thanks for looking into it. This issue is probably going to hit many of the distros too. 🙁
