### ISSUE TITLE
"Unable to find matching CELT codecs with other clients."

### ISSUE THREAD

**Issue by Ezwen** [flathub/info.mumble.Mumble#7]
When joining a server, I get the following message:
```
Unable to find matching CELT codecs with other clients. You will not be able to talk to all users.
```
and then I can neither speak nor hear others.

Maybe the flatpak is missing some codecs?

**Comment by JBBgameich** [comment]
I know the error message, however I could still speak to the others. Is this a new bug after upgrading to the new 19.08 freedesktop sdk? (mumble migrated roughly a week ago)

**Comment by Ezwen** [comment]
I'm pretty sure I did not have any problem last time I used mumble (a few months ago), so it's definitely possibly related to the new sdk!

**Comment by JBBgameich** [comment]
Assuming it builds fine, can you please test wether https://github.com/flathub/info.mumble.Mumble/pull/8 improves it for you?

**Comment by JBBgameich** [comment]
It might also help to check whether you have org.freedesktop.Platform.html5-codecs installed btw.

**Comment by Ezwen** [comment]
Sure, how can I install the build from #8?

**Comment by JBBgameich** [comment]
Once the bot has finished building it it will post installation instructions.

**Comment by Ezwen** [comment]
Just tried the build, but the problem remains :(

Then I tried to install the html5-codecs and I got:
```
Skipping: org.freedesktop.Platform.html5-codecs/x86_64/18.08 is already installed
```

**Comment by JBBgameich** [comment]
Since the issue appeared after the runtime upgrade, you are probably missing the html5 codecs for the new 19.08 runtime but have them installed for 18.08.

**Comment by Ezwen** [comment]
Indeed:
```
html5-codecs    org.freedesktop.Platform.html5-codecs    18.08       flathub     user
```
So I have to wait for the upgrade to 19.08?

**Comment by JBBgameich** [comment]
Not sure. I surprised the 19.08 extension doesn't exist yet :/

**Comment by adnub** [comment]
I'm noticing the same thing.
To work around the issue, I installed an older version via apt, copied /usr/lib/mumble/libcelt0.so.0.7.0 from it.
Then removed the older version, installed the flatpak version and put libcelt0.so.0.7.0 in the folder ~/.local/share/flatpak/app/info.mumble.Mumble/current/active/files/bin

Can you guys please add libcelt0.so.0.7.0 to the flatpak version?

**Comment by JBBgameich** [comment]
Should be resolved now. The celt codec was always included, but Mumble failed to find it in the flatpak filesystem structure.

**Comment by Ezwen** [comment]
Indeed the problem seems solved, thanks! :+1:
